[package]
name = "rogue"
version = "0.1.0"
authors = ["gguai"]

[dependencies]
tcod = { version = "0.11", features = ["serialization"] }
rand = "^0.3.9"
serde = "^0.9"
serde_derive = "^0.9"
serde_json = "^0.9"
bresenham = "*"